name: ffc-api-modifier

services:
  app:
    container_name: ffc-api-modifier-app
    build:
      context: .
      dockerfile: dev.Dockerfile
    image: ffc-api-modifier:local
    working_dir: /app
    command: bash -c "uv run fastapi dev --host 0.0.0.0 --port 8095"
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "${FFC_MODIFIER_PORT:-8095}:8095"

  app_test:
    container_name: ffc-api-modifier-test
    build:
      context: .
      dockerfile: dev.Dockerfile
    image: api-modifier-dev:local
    working_dir: /app
    command: >
      bash -c "
        set -e

        # Run Ruff to check code style
        uv run ruff check .

        # Check formatting with Ruff
        uv run ruff format --check --diff .

        # Run tests with pytest
        uv run pytest
      "
    volumes:
      - .:/app
    env_file:
      - .env

  bash:
    container_name: ffc-api-modifier-bash
    build:
      context: .
      dockerfile: dev.Dockerfile
    image: api-modifier-dev:local
    working_dir: /app
    command: bash
    stdin_open: true
    tty: true
    volumes:
      - .:/app
    env_file:
      - .env

  format:
    container_name: ffc-api-modifier-format
    build:
      context: .
      dockerfile: dev.Dockerfile
    image: api-modifier-dev:local
    working_dir: /app
    command: >
      bash -c "
        set -e
        # Run Ruff to fix code style
        uv run ruff check . --fix --fix-only --show-fixes

        # Run Ruff to format code
        uv run ruff format .
      "
    volumes:
      - .:/app
    env_file:
      - .env

  bandit:
    container_name: ffc-api-modifier-bandit
    build:
      context: .
      dockerfile: dev.Dockerfile
    image: api-modifier-dev:local
    working_dir: /app
    command: bash -c "uv run bandit -c pyproject.toml -r . -f json -o bandit.json"
    volumes:
      - .:/app
    env_file:
      - .env
