version: '3.8'

services:
  db:
    image: postgres:15
    container_name: api_modifier_postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecurepass
      POSTGRES_DB: users
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  db_test:
    image: postgres:15
    container_name: api_modifier_postgres_db_test
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecurepass
      POSTGRES_DB: test_database
    ports:
      - "5434:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data

  app_test:
    container_name: optscale_api_modifier_test
    build:
      context: .
      dockerfile: test.Dockerfile
    working_dir: /app
    command: bash -c ". /app/.venv/bin/activate && ruff check . && pytest"
    volumes:
      - .:/app
      - venv:/app/.venv
      - .env.test:/app/.env.test
    env_file:
      - .env

volumes:
  postgres_data:
  postgres_test_data:
  venv:
