[tool.poetry]
name = "optscale-api-modifier"
version = "0.1.0"
description = ""
authors = ["Antonio Di Mariano <antonio.dimariano@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.115.3"
python-dotenv = "^1.0.1"
httpx = "^0.27.2"
pydantic-settings = "^2.6.0"
uvicorn = "^0.32.0"
python-json-logger = "^2.0.7"
pyjwt = "^2.9.0"
python-decouple = "^3.8"
setuptools = "^75.2.0"
cython = "^3.0.11"
pydevd = "^3.2.2"
wheel = "^0.44.0"
pytest = "^8.3.3"
pytest-asyncio = "^0.24.0"
pytest-mock = "^3.14.0"
sqlmodel = "^0.0.22"
currency-codes = "^23.6.4"
pydantic = {extras = ["email"], version = "^2.9.2"}
greenlet = "^3.1.1"
exceptiongroup = "^1.1.0"
pytest-cov = "^6.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
